# Module 2 Discussion Notebook

## The Problem

I've not sure if I've encountered a system of equations involving more than two linear equations + more than two variables.

One hypothetical situation would be if there potentially a contracting situation in advertising where you had three similar products in place and the budget needs to be balanced for them on three variables: CPM (cost per mille, the fee for every 1,000 impressions[the views of an ad], fee, User fee, and data fees.

__Let's assume that we have the following:__

__1.25x+100y+1300z = $1,000,000 (Product A)__

__1.5x+250y+1100z = $1,000,000 (Product B)__

__1.15x+175y+1250z = $1,000,000 (Product C)__

CPM fees are $1.25, $1.50, $1.15

Fees per user are $100, $250, $175 per license.

Cost per million rows is $1,300, $1,100, and $1,250

Based on the wisdom of those above, we're to balance the budget between the three products.

Using the inverse method of solving we can do the following:

## The Solution

In [1]:
#first step is to import numpy so we can do some math
import numpy as np

#now let's convert our system of equations into something python can ingest
#we'll do a list of lists. three lists that are our equations in a list fed to numpy
#first list is 1.25x+100y+1300z as [1.25,100,1300]
#second list is 1.5x+250y+1100z as [1.5,250,1100]
#third list is 1.15x+175y+1250z as [1.15,175,1250]
#We're going to to then plug this into np.array since python natively does not support arrays, only lists
#and python can't do maths on lists without calling each element in a list
A = np.array([[1.25,100,1300],[1.5,250,1100],[1.15,175,1250]])

#the above might be visually confusing since it's horizontal.
#you can do the below as well using spaces to line them up vertically
#don't forget your commas when you do this!
#functionally, it's still just a 1-dimensional list
# A = np.array([
#              [1.25,100,1300], equation1
#              [1.5,250,1100], equation2
#              [1.15,175,1250] equation 3
#              ] -enclosing bracket for list of equations
#              ) -enclosing parenthesis for function np.array

#now we'll make the right hand side of the equation
#since the powers that be have decreed the budgets must be equal
#we can just do another list of [1000000,1000000,1000000]
B = [1000000,1000000,1000000]

#now we're going to use numpys built int functions and do our math
#step one is to call numpy via 'np'
#step two is call linalg.inv which gives us the inverse
#step three is also doing .dot which does the dot product for us
#note in step three np.linalg.inv and np.dot are two separate functions
#by doing it like this we save some space
#alternate is below:
#step1 = np.linalg.inv(A)
#step2 = step1.dot(B)
#print(step2)

X = np.linalg.inv(A).dot(B)

#print the answer!
print(X)

[132743.36283186    575.22123894    597.34513274]


## The verbose and formatted solution

In [31]:
A = np.array([
             [1,1,1], #equation1
             [394,1463,1684], #equation2
             [1,-2,0] #equation 3
             ] #enclosing bracket for list of equations
             ) #enclosing parenthesis for function np.array

B = [155,148980,0]

step1 = np.linalg.inv(A)
step2 = step1.dot(B)
print(step2)

[80. 40. 35.]


: 

In [11]:
A = np.array([
             [2,1], #equation1
             [503,1056], #equation2
             #[1.15,175,1250] #equation 3
             ] #enclosing bracket for list of equations
             ) #enclosing parenthesis for function np.array

B = [145,129325]

X = np.linalg.inv(A).dot(B)
print(X)

[ 14.78868863 115.42262275]


In [ ]:
A = np.array([
             [2,1,1], #equation1
             [503,1056,1489], #equation2
             [2,-1,0] #equation 3
             ] #enclosing bracket for list of equations
             ) #enclosing parenthesis for function np.array

B = [145,129325,0]

step1 = np.linalg.inv(A)
step2 = step1.dot(B)
print(step2)

In [24]:
arr1=np.array([[14000,19000,35000,50000],[17000,21000,27000,56000]])
arr2=np.array([[0.07,0,0,0],[0,0.11,0,0],[0,0,0.09,0],[0,0,0,0.22]])
answer=np.dot(arr1,arr2)
print(answer)


[[  980.  2090.  3150. 11000.]
 [ 1190.  2310.  2430. 12320.]]


In [26]:
t1=np.array([[3,-10],[-1,5]])
invt1=np.linalg.inv(t1)
rhs=np.array([1,3])
answer1=np.linalg.inv(t1).dot(rhs)
print(answer1)

[7. 2.]


In [29]:
rhs=np.array([20,-6,-20])
soe=np.array([[-1,5,-5],[2,-2,1],[3,-4,6]])
answer2=np.linalg.inv(soe).dot(rhs)
print(answer2)

[ 0.  2. -2.]
